<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CarSeeder extends Seeder
{
    /**
     * Unsplash photo ids, resolved to a sized CDN url by img().
     */
    private const PHOTOS = [
        'blue_coupe' => 'photo-1552519507-da3b142c6e3d',
        'porsche' => 'photo-1503376780353-7e6692767b70',
        'mustang' => 'photo-1494976388531-d1058494cdd8',
        'lambo' => 'photo-1583121274602-3e2820c69888',
        'white_suv' => 'photo-1568605117036-5fe5e7bab0b7',
        'bmw' => 'photo-1502877338535-766e1452684a',
        'mercedes' => 'photo-1549317661-bd32c8ce0db2',
        'tesla' => 'photo-1605559424843-9e4c228bf1c2',
        'grey_sedan' => 'photo-1555215695-3004980ad54e',
        'classic' => 'photo-1541899481282-d53bffe3c35d',
        'roadster' => 'photo-1533473359331-0135ef1b58bf',
        'tesla_road' => 'photo-1580273916550-e323be2ae537',
        'suv_dark' => 'photo-1617469767053-d3b523a0b982',
        'hatch' => 'photo-1616422285623-13ff0162193c',
        'range' => 'photo-1493238792000-8113da705763',
        'jeep' => 'photo-1544636331-e26879cd4d9b',
        'front' => 'photo-1503736334956-4c8f8e92946d',
        'road' => 'photo-1449965408869-eaa3f722e40d',
        'garage' => 'photo-1502161254066-6c74afbf07aa',
        'wagon' => 'photo-1567818735868-e71b99932e29',
        'interior' => 'photo-1492144534655-ae79c964c9d7',
        'showroom' => 'photo-1550355291-bbee04a92027',
        'truck' => 'photo-1489824904134-891ab64532f1',
    ];

    public static function img(string $key, int $width = 1200): string
    {
        return 'https://images.unsplash.com/'.self::PHOTOS[$key]."?auto=format&fit=crop&w={$width}&q=80";
    }

    public function run(): void
    {
        foreach ($this->cars() as $car) {
            $car['slug'] = Str::slug($car['year'].' '.$car['title']);
            $car['image'] = self::img($car['image']);
            $car['gallery'] = array_map(fn (string $key) => self::img($key), $car['gallery']);

            Car::updateOrCreate(['slug' => $car['slug']], $car);
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function cars(): array
    {
        return [
            [
                'title' => 'Porsche 911 Carrera S',
                'brand' => 'Porsche',
                'model' => '911 Carrera S',
                'year' => 2023,
                'body_type' => 'Coupe',
                'condition' => 'Used',
                'city' => 'Miami',
                'state' => 'Florida',
                'price' => 128500,
                'mileage' => 8200,
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'seats' => 4,
                'horsepower' => 443,
                'exterior_color' => 'Guards Red',
                'badge' => 'Featured',
                'image' => 'porsche',
                'gallery' => ['porsche', 'blue_coupe', 'interior', 'garage'],
                'features' => ['Sport Chrono Package', 'Adaptive Cruise Control', 'Bose Surround Sound', 'Ventilated Seats', 'Lane Keep Assist', '360° Camera'],
                'description' => 'A meticulously maintained 911 Carrera S with the Sport Chrono package. Two owners from new, full Porsche service history, and never tracked. The flat-six pulls hard to redline and the PDK shifts are seamless.',
                'is_featured' => true,
            ],
            [
                'title' => 'Tesla Model S Plaid',
                'brand' => 'Tesla',
                'model' => 'Model S Plaid',
                'year' => 2024,
                'body_type' => 'Sedan',
                'condition' => 'New',
                'city' => 'Austin',
                'state' => 'Texas',
                'price' => 94990,
                'mileage' => 120,
                'transmission' => 'Automatic',
                'fuel_type' => 'Electric',
                'seats' => 5,
                'horsepower' => 1020,
                'exterior_color' => 'Pearl White',
                'badge' => 'New',
                'image' => 'tesla',
                'gallery' => ['tesla', 'tesla_road', 'interior', 'road'],
                'features' => ['Full Self-Driving', 'Tri-Motor AWD', 'Glass Roof', 'Premium Audio', 'Heated Seats', 'Autopilot'],
                'description' => 'Delivery-mileage Model S Plaid with tri-motor all-wheel drive and a 0-60 time under two seconds. Includes Full Self-Driving capability and the full factory warranty.',
                'is_featured' => true,
            ],
            [
                'title' => 'Ford Mustang GT Premium',
                'brand' => 'Ford',
                'model' => 'Mustang GT',
                'year' => 2022,
                'body_type' => 'Coupe',
                'condition' => 'Used',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'price' => 46700,
                'mileage' => 21400,
                'transmission' => 'Manual',
                'fuel_type' => 'Petrol',
                'seats' => 4,
                'horsepower' => 450,
                'exterior_color' => 'Shadow Black',
                'badge' => 'Hot Deal',
                'image' => 'mustang',
                'gallery' => ['mustang', 'classic', 'interior', 'garage'],
                'features' => ['5.0L V8', 'Active Exhaust', 'Brembo Brakes', 'Apple CarPlay', 'Recaro Seats', 'Line Lock'],
                'description' => 'The GT Premium with the six-speed manual and active valve exhaust. Garage kept, adult owned, and priced to move below comparable listings in the region.',
                'is_featured' => true,
            ],
            [
                'title' => 'BMW M4 Competition',
                'brand' => 'BMW',
                'model' => 'M4 Competition',
                'year' => 2023,
                'body_type' => 'Coupe',
                'condition' => 'Used',
                'city' => 'New York',
                'state' => 'New York',
                'price' => 82300,
                'mileage' => 12750,
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'seats' => 4,
                'horsepower' => 503,
                'exterior_color' => 'Isle of Man Green',
                'badge' => 'Featured',
                'image' => 'bmw',
                'gallery' => ['bmw', 'front', 'interior', 'showroom'],
                'features' => ['M xDrive', 'Carbon Fibre Trim', 'Head-Up Display', 'Harman Kardon Audio', 'Adaptive M Suspension', 'Wireless Charging'],
                'description' => 'M4 Competition finished in Isle of Man Green over Silverstone leather. Carbon exterior package, still under the factory maintenance plan.',
                'is_featured' => true,
            ],
            [
                'title' => 'Mercedes-Benz E 450 4MATIC',
                'brand' => 'Mercedes-Benz',
                'model' => 'E 450',
                'year' => 2023,
                'body_type' => 'Sedan',
                'condition' => 'Certified',
                'city' => 'Los Angeles',
                'state' => 'California',
                'price' => 68900,
                'mileage' => 15900,
                'transmission' => 'Automatic',
                'fuel_type' => 'Hybrid',
                'seats' => 5,
                'horsepower' => 375,
                'exterior_color' => 'Obsidian Black',
                'badge' => null,
                'image' => 'mercedes',
                'gallery' => ['mercedes', 'grey_sedan', 'interior', 'road'],
                'features' => ['MBUX Dual Screens', 'Burmester Audio', 'Air Body Control', 'Massage Seats', 'Ambient Lighting', 'Blind Spot Assist'],
                'description' => 'Certified pre-owned E 450 with the mild-hybrid inline-six. Air suspension, massage seats, and a two-year unlimited-mileage warranty included.',
                'is_featured' => true,
            ],
            [
                'title' => 'Lamborghini Huracán EVO',
                'brand' => 'Lamborghini',
                'model' => 'Huracán EVO',
                'year' => 2022,
                'body_type' => 'Coupe',
                'condition' => 'Used',
                'city' => 'Miami',
                'state' => 'Florida',
                'price' => 289000,
                'mileage' => 4300,
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'seats' => 2,
                'horsepower' => 631,
                'exterior_color' => 'Verde Mantis',
                'badge' => 'Hot Deal',
                'image' => 'lambo',
                'gallery' => ['lambo', 'showroom', 'interior', 'garage'],
                'features' => ['5.2L V10', 'Rear-Wheel Steering', 'Lifting System', 'Carbon Ceramic Brakes', 'Sport Seats', 'Telemetry System'],
                'description' => 'Naturally aspirated V10 Huracán EVO with lifting system and carbon ceramic brakes. Clean history report, ceramic coated, and fully serviced.',
                'is_featured' => true,
            ],
            [
                'title' => 'Range Rover Sport HSE',
                'brand' => 'Land Rover',
                'model' => 'Range Rover Sport',
                'year' => 2023,
                'body_type' => 'SUV',
                'condition' => 'Certified',
                'city' => 'Seattle',
                'state' => 'Washington',
                'price' => 79400,
                'mileage' => 18600,
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 5,
                'horsepower' => 355,
                'exterior_color' => 'Santorini Black',
                'badge' => null,
                'image' => 'range',
                'gallery' => ['range', 'suv_dark', 'interior', 'road'],
                'features' => ['Terrain Response 2', 'Panoramic Roof', 'Meridian Audio', 'Air Suspension', 'Heated Steering Wheel', 'Tow Package'],
                'description' => 'HSE trim with air suspension and the full off-road pack. Dealer maintained since new with every service recorded.',
                'is_featured' => false,
            ],
            [
                'title' => 'Audi Q7 Prestige',
                'brand' => 'Audi',
                'model' => 'Q7',
                'year' => 2024,
                'body_type' => 'SUV',
                'condition' => 'New',
                'city' => 'Denver',
                'state' => 'Colorado',
                'price' => 74250,
                'mileage' => 45,
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'seats' => 7,
                'horsepower' => 335,
                'exterior_color' => 'Glacier White',
                'badge' => 'New',
                'image' => 'white_suv',
                'gallery' => ['white_suv', 'front', 'interior', 'showroom'],
                'features' => ['Quattro AWD', 'Virtual Cockpit', 'Bang & Olufsen 3D', 'Third Row Seating', 'Adaptive Air Suspension', 'Park Assist'],
                'description' => 'Brand-new Q7 Prestige with the Bang & Olufsen 3D sound system and seven-seat layout. Full factory warranty and free scheduled maintenance.',
                'is_featured' => false,
            ],
            [
                'title' => 'Jeep Wrangler Rubicon',
                'brand' => 'Jeep',
                'model' => 'Wrangler Rubicon',
                'year' => 2022,
                'body_type' => 'SUV',
                'condition' => 'Used',
                'city' => 'Phoenix',
                'state' => 'Arizona',
                'price' => 48900,
                'mileage' => 27300,
                'transmission' => 'Manual',
                'fuel_type' => 'Petrol',
                'seats' => 5,
                'horsepower' => 285,
                'exterior_color' => 'Firecracker Red',
                'badge' => null,
                'image' => 'jeep',
                'gallery' => ['jeep', 'truck', 'interior', 'road'],
                'features' => ['Rock-Trac 4x4', 'Removable Doors', 'Locking Differentials', 'Sway Bar Disconnect', 'Skid Plates', '33" All-Terrains'],
                'description' => 'Rubicon with the six-speed manual, factory lockers, and a lift kit installed by the selling dealer. Trail rated and ready.',
                'is_featured' => false,
            ],
            [
                'title' => 'Toyota Corolla Hybrid LE',
                'brand' => 'Toyota',
                'model' => 'Corolla Hybrid',
                'year' => 2024,
                'body_type' => 'Hatchback',
                'condition' => 'New',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'price' => 26400,
                'mileage' => 60,
                'transmission' => 'Automatic',
                'fuel_type' => 'Hybrid',
                'seats' => 5,
                'horsepower' => 138,
                'exterior_color' => 'Celestite Grey',
                'badge' => 'Hot Deal',
                'image' => 'hatch',
                'gallery' => ['hatch', 'grey_sedan', 'interior', 'road'],
                'features' => ['Toyota Safety Sense 3.0', '50+ MPG Combined', 'Apple CarPlay', 'Adaptive Cruise', 'Blind Spot Monitor', 'Keyless Start'],
                'description' => 'The value pick of the lineup. Better than 50 mpg combined, Toyota Safety Sense 3.0 standard, and one of the lowest cost-of-ownership figures on the market.',
                'is_featured' => false,
            ],
            [
                'title' => 'Mazda MX-5 Miata RF',
                'brand' => 'Mazda',
                'model' => 'MX-5 Miata RF',
                'year' => 2023,
                'body_type' => 'Convertible',
                'condition' => 'Used',
                'city' => 'San Diego',
                'state' => 'California',
                'price' => 33800,
                'mileage' => 9800,
                'transmission' => 'Manual',
                'fuel_type' => 'Petrol',
                'seats' => 2,
                'horsepower' => 181,
                'exterior_color' => 'Soul Red Crystal',
                'badge' => null,
                'image' => 'roadster',
                'gallery' => ['roadster', 'classic', 'interior', 'road'],
                'features' => ['Retractable Hardtop', 'Limited Slip Differential', 'Bilstein Dampers', 'Bose Audio', 'Recaro Seats', 'BBS Wheels'],
                'description' => 'RF with the retractable hardtop, six-speed manual, and the Club package. Low mileage, never seen winter roads.',
                'is_featured' => false,
            ],
            [
                'title' => 'Volvo V60 Cross Country',
                'brand' => 'Volvo',
                'model' => 'V60 Cross Country',
                'year' => 2023,
                'body_type' => 'Wagon',
                'condition' => 'Certified',
                'city' => 'Boston',
                'state' => 'Massachusetts',
                'price' => 52100,
                'mileage' => 16400,
                'transmission' => 'Automatic',
                'fuel_type' => 'Hybrid',
                'seats' => 5,
                'horsepower' => 295,
                'exterior_color' => 'Fusion Red',
                'badge' => null,
                'image' => 'wagon',
                'gallery' => ['wagon', 'front', 'interior', 'showroom'],
                'features' => ['Pilot Assist', 'Panoramic Roof', 'Harman Kardon Audio', 'Heated Rear Seats', 'Power Tailgate', 'AWD'],
                'description' => 'Certified V60 Cross Country with the raised suspension and all-wheel drive. The practical answer to a mid-size SUV, with far better road manners.',
                'is_featured' => false,
            ],
        ];
    }
}
